package cn.budwing.stock.vo;

// Generated 2014-12-6 22:33:32 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Fund generated by hbm2java
 */
public class Fund implements java.io.Serializable {

	private String id;
	private Float amount;
	private Date date;
	private String reason;
	private Float balance;
	private String notes;

	public Fund() {
	}

	public Fund(String id) {
		this.id = id;
	}

	public Fund(String id, Float amount, Date date, String reason,
			Float balance, String notes) {
		this.id = id;
		this.amount = amount;
		this.date = date;
		this.reason = reason;
		this.balance = balance;
		this.notes = notes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
