package cn.budwing.stock.vo;

// Generated 2014-12-6 22:33:32 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Selling generated by hbm2java
 */
public class Selling implements java.io.Serializable {

	private String id;
	private String buyId;
	private String stockId;
	private String stockCode;
	private String stockName;
	private Date date;
	private Float price;
	private Integer amount;
	private String notes;

	public Selling() {
	}

	public Selling(String id) {
		this.id = id;
	}

	public Selling(String id, String buyId, String stockId, String stockCode,
			String stockName, Date date, Float price, Integer amount,
			String notes) {
		this.id = id;
		this.buyId = buyId;
		this.stockId = stockId;
		this.stockCode = stockCode;
		this.stockName = stockName;
		this.date = date;
		this.price = price;
		this.amount = amount;
		this.notes = notes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBuyId() {
		return this.buyId;
	}

	public void setBuyId(String buyId) {
		this.buyId = buyId;
	}

	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	public String getStockCode() {
		return this.stockCode;
	}

	public void setStockCode(String stockCode) {
		this.stockCode = stockCode;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
