package cn.budwing.stock.vo;

// Generated 2014-12-6 22:33:32 by Hibernate Tools 4.3.1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private String id;
	private String code;
	private String name;
	private String notes;

	public Stock() {
	}

	public Stock(String id) {
		this.id = id;
	}

	public Stock(String id, String code, String name, String notes) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.notes = notes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
