package com.github.budwing.pattern.monitor.vo;

// Generated 2014-12-6 22:33:32 by Hibernate Tools 4.3.1

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private String id;
	private String code;
	/**
	 * 加了前缀的代码
	 * 沪市sh，深市sz
	 */
	private String prefixedCode;
	private String name;
	private String notes;


	public Stock() {
		super();
	}

	public Stock(String code) {
		super();
		this.code = code;
	}

	public Stock(String code, String name) {
		super();
		this.code = code;
		this.name = name;
	}

	public Stock(String code, String name, String notes) {
		super();
		this.code = code;
		this.name = name;
		this.notes = notes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}
	
	/**
	 * 判断是否为沪市
	 * @return
	 */
	public boolean isSh() {
		return code.startsWith("6");
	}
	
	public String getPrefixedCode() {
		if(prefixedCode==null || prefixedCode.isEmpty()) {
			StringBuilder sb = new StringBuilder(code);
			if(isSh()) {
				sb.insert(0,"sh");
			} else {
				sb.insert(0, "sz");
			}
			prefixedCode = sb.toString();
		}
		
		return prefixedCode;
	}

}
